---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(ggpubr)
```


Load functions

```{r}
source("simulation.R")
```

Parameters for plotting

```{r}
my.theme<-theme(axis.text=element_text(size=12),
                axis.title = element_text(size = 14),
                legend.position = "top",
                legend.text=element_text(size=10),
                legend.title = element_text(size=12),
                plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
                axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)),
                axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)))
```






[CURRENT VERSION] -> only selection-driven. No storage of distance_ancestry.

```{r}

pars = list()

pars$av_r = 0.2 # range of the niche

# PROBABILITY OF MUTATION

pars$u_max = 0.15 # mutation probability
pars$d = 0.5 # Decrease speed of the establishment probability
pars$I_max = 40 # Maximal number of interactioning species

pars$beta_n = 1 # parameter of the beta distribution 


# STRENGTH OF NEUTRAL-DRIVEN EVOLUTION

pars$SN = 0.5 # strength for neutral-driven evolution


# PROBABILITY OF ESTABLISHMENT



# strength of selection-driven selection is 1 - SN
pars$estab_prob_neutral = 0.4 # neutral probability of establishment

# Competition

pars$u_0neg = 0.075 # Asymptotic establishment probability with infinite competitive interactions
pars$u_1neg = 2 # Establishment probability with absence of competitive interactions
pars$a_uneg = 0.075 # Shape of the exponential decay of the colonization - interaction relationship

# Facilitation & Foodweb

pars$u_0pos = 1  
pars$u_1pos = -1 
pars$a_upos = 0.45 

# PROBABILITY OF EXTINCTION

pars$ext_prob_neutral = 0.1 # neutral probability of extinction


# Competition

pars$e_0neg = 0.5 # Asymptotic extinction probability with infinite negative interactions
pars$a_eneg = 0.025 # Shape of the exponential decay of the negative extinction - interaction relationship
pars$e_1neg = 1  # Extinction probability with absence of interactions

# Facilitation & Foodweb

pars$e_0pos = 0.01 
pars$e_1pos = 5.19 
pars$a_epos = 1.2 



pars$Sbasal = 25 # number of basal species
pars$Smax = 1000 # Maximal number of species allowed




```


# set parameters simulation

```{r}
nsteps = 250 # Set the maximum timestep per simulation
nsim = 3 # Set the number of simulations

# Vector to record number of simulation needed to reach X valid simulations
needed_sim_pos <- c(rep(NA, nsim))
needed_sim_neg <- c(rep(NA, nsim))
```

### Seeds record matrix

```{r}
# List of used seed per simulation batch
reccorded_seed_pos_list <- list()
reccorded_seed_neg_list <- list()

seed_list <- NULL # Set an object to record seed that will be used to launch simulations

```


Run simulation

```{r}

total_nb_sim <- 0
b <- 1

pars$interaction = 1

seed = 1


for (int in 0:2) {
  
  pars$int = int # Define the interaction type: 0 = competition ; 1 = facilitation
  
  successful_sim <- 1 # Set the count of simulations
  
  
  if(pars$int == 0){
    print("Competition interctions")
  } else if(pars$int == 1){
    print("Facilitation interctions")
  }else if(pars$int == 2){
    print("Foodweb interctions")
  }
  
  seed_record <- c(rep(NA, nsim)) # Set the vector to record the seed that have been used
  
  
  
  while(successful_sim < nsim +1){
    
    
    seed <- sample.int(80000, 1) # Pick a random number, this number will be the seed for one simulation
    print(seed)
    
    # If a seed have already been tested, pick another one
    if(length(which(seed_list == seed)) != 0){
      while(seed %in% seed_list){
        seed <- sample.int(80000, 1)
      }
    }
    
    seed_list <- c(seed_list, seed) # Add the seed
    
    
    
    
    
    # SIMULATION
    
    simulation <- sim_model(seed = runif(1), 
                            pars, 
                            nsteps = nsteps)
    
    total_nb_sim <- total_nb_sim +1 # Count the total amount of simulations
    
    
    # Test if we have enough species at the timestep 150 in the simulation
    success <- sum(simulation$pres[150,])
    #print(paste0("Success = ", success))
    
    if(success >= 20){
      #print("the simulation has more than 19 species at the time step 150")
      seed_record[successful_sim] <- seed # Record seed which alows us to have "good" simulation
      res_sim <- list(simulation_number = paste0("simulation", successful_sim), 
                      seed = seed,
                      parameters = pars, 
                      presence_matrix = simulation$pres, 
                      traits_df = simulation$traits,
                      parentage_matrix = simulation$anc,
                      extinxction_matrix = simulation$extinct, 
                      network_list = simulation$L_list
                      # anc_dist_table = simulation$dist_anc, 
                      # list_anc_dist = simulation$list_dist_anc
      ) # Record results from the simulation
      
      
      print(paste("simulation ", successful_sim, "sur", nsim))
      successful_sim <- successful_sim + 1 # Count the amount of "good" simulations
      
      
      
      
      # Save simulations results data
      if(pars$int == 0){
        path <- paste0("list_res_comp_", successful_sim, ".rds")
        saveRDS(res_sim, file = path) #Change if interaction tyep = 0 (competition)
      } else if(pars$int == 1){
        path <- paste0("list_res_fac_", successful_sim, ".rds")
        saveRDS(res_sim, file = path) #Change if interaction tyep = 0 (competition)
      } else if(pars$int == 2){
        path <- paste0("list_res_fw_", successful_sim, ".rds")
        saveRDS(res_sim, file = path) #Change if interaction tyep = 0 (competition)
      }
      
      
      rm(res_sim)
      
      
    }
    
  }
  
}






```



# Explore results

Competition

```{r}
res <- readRDS("list_res_comp_2.rds")


# count number of timesteps where there are spp

list_simulation1 <- list_res

n_steps <- length(list_simulation1$network_list)



```




## N values with time

```{r}



res_spp = data.frame(matrix(ncol=2,
                      nrow=0, 
                      dimnames=list(NULL, c("step", "n values")))) #makes an empty dataframe

res_mean = data.frame(matrix(ncol=2,
                      nrow=0, 
                      dimnames=list(NULL, c("step", "n values")))) 


for (i in 1:nsteps) {
  
  pres_stepi <- which(pres[i,] == 1)
  traits_stepi <- traits[pres_stepi, "n"]
  
  vec_step <- rep(i, times = length(traits_stepi))
  
  
  
  res.add <- data.frame("step" = vec_step, 
                               "n values" = traits_stepi)
  
  res_spp <- rbind(res_spp, res.add)
  

  
  res.add1 <- data.frame("step" = i, 
                                "n values" = mean(traits_stepi))
  
  res_mean <- rbind(res_mean, res.add1)
  
  
}

ggarrange(
  
  ggplot(res_spp, aes(x = step, y = n.values)) +
    geom_point(alpha = 0.2)+
    ggtitle("spp n values")+
    theme_classic()+
    my.theme+
    ylim(0,1),
  
  
  
  ggplot(res_mean, aes(x = step, y = n.values)) +
    geom_point(alpha = 0.2)+
    ggtitle("mean n values")+
    theme_classic()+
    my.theme+
    ylim(0,1),
  
  nrow = 1, 
  ncol = 2
  
  
)


```



## Speces richness with time





```{r}
# Plot mean trait value
pres = res$pres
traits = res$traits
t=matrix(traits[,1],nr = nsteps, nc = ncol(pres),byrow=TRUE)
mean_trait = apply(pres*t,1,sum,na.rm=T)/apply(pres,1,sum)
plot(c(1:nsteps),mean_trait, type = "l")

```



```{r}
# Plot diversification dynamics
pres = res$pres
traits = res$traits
Stot = ncol(pres)
S = apply(pres,1,sum)

dev.new(width = 5, height = 4)
par(mar = c(5,6,2,1))
plot(c(1:nsteps),S,type = "l", xlab = "Time", ylab = "Species richness",cex.axis = 1.25, cex.lab = 1.5,lwd = 1.5)
```

```{r}
##############################
# Plot the trait distribution over time
pres = res$pres
traits = res$traits

Time = c(1:nrow(pres))

plot(Time[pres[,1]==1],rep(traits[1,1],sum(pres[,1])),xlim = c(1,nsteps),ylim = c(0,1), pch = 19, cex = 0.3, xlab = "Time", ylab = "Niche position")
for(i in 1:Stot) points(Time[pres[,i]==1],rep(traits[i,1],sum(pres[,i])),cex = 0.3,pch = 19)

```



